language: csharp
mono: none
sudo: required
dotnet: 2.2

branches:
  only:
    - master

script: 
  - cd ./src
  - dotnet restore
  - dotnet build
  - cd ../

cache:
  directories:
  - bin

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

notifications:
  email:
    - haofefe@163.com
